/// 所有可能的用户操作
#[derive(Debug, Clone)]
pub enum Action {
    Quit,
    MoveUp,
    MoveDown,
    JumpTop,
    JumpBottom,
    PageUp,
    PageDown,
    Select,
    EnterSearch,
    ExitSearch,
    SearchInput(char),
    SearchBackspace,
    SearchClear,
    CycleSortField,
    ToggleSortOrder,
    ToggleProjectFilter,
    DeleteSelected,
    MarkSelected,
    DeleteMarked,
    ExportMarkdown,
    ExportJson,
    TogglePreview,
    FocusPreview,
    UnfocusPreview,
    ScrollPreviewUp,
    ScrollPreviewDown,
    ShowHelp,
    HideHelp,
    ConfirmYes,
    ConfirmNo,
    #[allow(dead_code)]
    Resize(u16, u16),
}
